### ISSUE TITLE
[UX] - Small layout shift on nav bar on initial load

### ISSUE THREAD

**Issue by minimalsm** [ethereum/geth-website#98]
_Note: I'm spamming refresh to show the bug. It only happens once._

![a558e134c4017706a26529e62949b0ac](https://user-images.githubusercontent.com/62268199/205068722-5e633908-a11a-4912-afb6-137bffa9c598.gif)

**Comment by wackerow** [comment]
I believe this may be related to the hydration issues we've been getting in dev
<img width="826" alt="image" src="https://user-images.githubusercontent.com/54227730/206049462-1c519309-9229-42f2-84d6-690812241fd8.png">

```log
Warning: Expected server HTML to contain a matching <a> in <a>.
    at a
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Link2 (webpack-internal:///./node_modules/@chakra-ui/layout/dist/index.esm.js:452:83)
    at a
    at LinkComponent (webpack-internal:///./node_modules/next/dist/client/link.js:102:23)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at eval (webpack-internal:///./node_modules/@chakra-ui/layout/dist/index.esm.js:714:5)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Flex2 (webpack-internal:///./node_modules/@chakra-ui/layout/dist/index.esm.js:273:11)
    at Header (webpack-internal:///./src/components/UI/Header.tsx:24:108)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Container2 (webpack-internal:///./node_modules/@chakra-ui/layout/dist/index.esm.js:206:83)
    at Layout (webpack-internal:///./src/components/layouts/Layout.tsx:17:11)
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/lib/index.js:96:23)
    at EnvironmentProvider (webpack-internal:///./node_modules/@chakra-ui/react-env/dist/index.esm.js:121:11)
    at ColorModeProvider (webpack-internal:///./node_modules/@chakra-ui/color-mode/dist/index.esm.js:158:5)
    at ThemeProvider (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:96:64)
    at ThemeProvider (webpack-internal:///./node_modules/@chakra-ui/system/dist/index.esm.js:112:11)
    at ChakraProvider (webpack-internal:///./node_modules/@chakra-ui/provider/dist/index.esm.js:21:5)
    at ChakraProvider (webpack-internal:///./node_modules/@chakra-ui/react/dist/index.esm.js:245:3)
    at App (webpack-internal:///./src/pages/_app.tsx:22:11)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:62:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:3209)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:6089)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:60:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:173:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:346:11)

react-dom.development.js?ac89:12507 Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js?ac89:12507:1)
    at tryToClaimNextHydratableInstance (react-dom.development.js?ac89:12520:1)
    at updateHostComponent (react-dom.development.js?ac89:19902:1)
    at beginWork (react-dom.development.js?ac89:21618:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?ac89:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?ac89:4213:1)
    at invokeGuardedCallback (react-dom.development.js?ac89:4277:1)
    at beginWork$1 (react-dom.development.js?ac89:27451:1)
    at performUnitOfWork (react-dom.development.js?ac89:26557:1)
    at workLoopSync (react-dom.development.js?ac89:26466:1)
    at renderRootSync (react-dom.development.js?ac89:26434:1)
    at performConcurrentWorkOnRoot (react-dom.development.js?ac89:25738:1)
    at workLoop (scheduler.development.js?bcd2:266:1)
    at flushWork (scheduler.development.js?bcd2:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?bcd2:533:1)

next-dev.js?3515:20 Warning: An error occurred during hydration. The server HTML was replaced with client content in <div>. 
See more info here: https://nextjs.org/docs/messages/react-hydration-error

next-dev.js?3515:20 Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
    at a
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Link2 (webpack-internal:///./node_modules/@chakra-ui/layout/dist/index.esm.js:452:83)
    at a
    at LinkComponent (webpack-internal:///./node_modules/next/dist/client/link.js:102:23)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at eval (webpack-internal:///./node_modules/@chakra-ui/layout/dist/index.esm.js:714:5)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Flex2 (webpack-internal:///./node_modules/@chakra-ui/layout/dist/index.esm.js:273:11)
    at Header (webpack-internal:///./src/components/UI/Header.tsx:24:108)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Container2 (webpack-internal:///./node_modules/@chakra-ui/layout/dist/index.esm.js:206:83)
    at Layout (webpack-internal:///./src/components/layouts/Layout.tsx:17:11)
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/lib/index.js:96:23)
    at EnvironmentProvider (webpack-internal:///./node_modules/@chakra-ui/react-env/dist/index.esm.js:121:11)
    at ColorModeProvider (webpack-internal:///./node_modules/@chakra-ui/color-mode/dist/index.esm.js:158:5)
    at ThemeProvider (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:96:64)
    at ThemeProvider (webpack-internal:///./node_modules/@chakra-ui/system/dist/index.esm.js:112:11)
    at ChakraProvider (webpack-internal:///./node_modules/@chakra-ui/provider/dist/index.esm.js:21:5)
    at ChakraProvider (webpack-internal:///./node_modules/@chakra-ui/react/dist/index.esm.js:245:3)
    at App (webpack-internal:///./src/pages/_app.tsx:22:11)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:62:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:3209)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:6089)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:60:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:173:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:346:11)

6react-dom.development.js?ac89:12507 Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js?ac89:12507:1)
    at tryToClaimNextHydratableInstance (react-dom.development.js?ac89:12520:1)
    at updateHostComponent (react-dom.development.js?ac89:19902:1)
    at beginWork (react-dom.development.js?ac89:21618:1)
    at beginWork$1 (react-dom.development.js?ac89:27426:1)
    at performUnitOfWork (react-dom.development.js?ac89:26557:1)
    at workLoopSync (react-dom.development.js?ac89:26466:1)
    at renderRootSync (react-dom.development.js?ac89:26434:1)
    at performConcurrentWorkOnRoot (react-dom.development.js?ac89:25738:1)
    at workLoop (scheduler.development.js?bcd2:266:1)
    at flushWork (scheduler.development.js?bcd2:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?bcd2:533:1)

react-dom.development.js?ac89:19849 Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
    at updateHostRoot (react-dom.development.js?ac89:19849:1)
    at beginWork (react-dom.development.js?ac89:21615:1)
    at beginWork$1 (react-dom.development.js?ac89:27426:1)
    at performUnitOfWork (react-dom.development.js?ac89:26557:1)
    at workLoopSync (react-dom.development.js?ac89:26466:1)
    at renderRootSync (react-dom.development.js?ac89:26434:1)
    at recoverFromConcurrentError (react-dom.development.js?ac89:25850:1)
    at performConcurrentWorkOnRoot (react-dom.development.js?ac89:25750:1)
    at workLoop (scheduler.development.js?bcd2:266:1)
    at flushWork (scheduler.development.js?bcd2:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?bcd2:533:1)
```

I don't see any improperly nested anchor tags, but would need to look closer

**Comment by wackerow** [comment]
Also noting, I think that flash that we still seem to inevitably get on refresh is a known Chakra-UI bug:
https://chakra-ui.com/docs/styled-system/color-mode#color-mode-flash-issue

But the layout shift should now gone with #140
